[versions]
agp = "8.5.1"
appcompatVersion = "1.7.0"
glide = "4.15.1"
glideVersion = "4.16.0"
googleApiClientAndroid = "1.35.0"
googleApiClientAndroidVersion = "1.33.2"
googleApiClientGson = "2.2.0"
googleApiServicesDrive = "v3-rev197-1.25.0"
googleApiServicesDriveVersion = "v3-rev305-1.25.0"
googleHttpClientGson = "1.43.3"
googlePlayServicesAuth = "20.7.0"
gradle = "8.10"
gradleVersion = "8.1.4"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinGradlePlugin = "1.9.0"
kotlinxCoroutinesAndroid = "1.8.1"
lifecycleRuntimeKtx = "2.8.4"
activityCompose = "1.9.1"
composeBom = "2024.06.00"
constraintlayout = "2.1.4"
appcompat = "1.7.0"
material = "1.12.0"
materialVersion = "1.11.0"
picasso = "2.71828"
playServicesAuth = "21.3.0"
recyclerview = "1.3.2"
roomVersion = "2.6.1"
ucrop = "2.2.8"
zip4j = "2.9.0"
flexbox = "3.0.0"



[libraries]
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-v4160 = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
gms-play-services-auth-v2070 = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServicesAuth" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-client-android-v1332 = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroidVersion" }
google-api-client-gson = { module = "com.google.api-client:google-api-client-gson", version.ref = "googleApiClientGson" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDrive" }
google-api-services-drive-vv3rev3051250 = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDriveVersion" }
google-http-client-gson = { module = "com.google.http-client:google-http-client-gson", version.ref = "googleHttpClientGson" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gradle-v813 = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

